---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
# https://docs.readthedocs.com/platform/stable/config-file/v2.html#formats
# pdf, epub, and htmlzip output is not yet supported when using MkDocs.
formats: all
# https://docs.readthedocs.com/platform/stable/config-file/v2.html#uv
python:
   install:
      - method: uv
        command: sync
        groups:
           - docs
        extras:
           # rdf4j extra is needed to document the modules in rdflib.contrib.rdf4j
           - rdf4j

# https://docs.readthedocs.com/platform/stable/config-file/v2.html#configuration-file-reference
build:
  os: "ubuntu-24.04"
  tools:
    python: "3"

mkdocs:
  configuration: mkdocs.yml
